# LIVE
; recipient_emails = 
; cc_emails = 
; bcc_emails = dhananjani.d@algospring.com, thevindu.r@algospring.com, akalanka.d@algospring.com

# TESTING
recipient_emails = dhananjani.d@algospring.com
cc_emails = akalanka.d@algospring.com
bcc_emails = 
